#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Quiz.Resource", IsApplication=true)]

namespace Quiz
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_up = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int ListViewHighlighted = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int ListViewSelected = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btnLoginStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btnRegisterStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ProgressBarStyle = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080012
			public const int a0 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int a1 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int a2 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int a3 = 2131230741;
			
			// aapt resource value: 0x7f080001
			public const int btnAddCategory = 2131230721;
			
			// aapt resource value: 0x7f08000b
			public const int btnAddQuestion = 2131230731;
			
			// aapt resource value: 0x7f08001f
			public const int btnAddUser = 2131230751;
			
			// aapt resource value: 0x7f08000e
			public const int btnLogOut = 2131230734;
			
			// aapt resource value: 0x7f080006
			public const int btnLogin = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int btnMenuIn = 2131230724;
			
			// aapt resource value: 0x7f080018
			public const int btnOdpowiedz = 2131230744;
			
			// aapt resource value: 0x7f08000d
			public const int btnRanking = 2131230733;
			
			// aapt resource value: 0x7f080008
			public const int btnRegister = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int btnSelectCategory = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int btnToAddCategory = 2131230732;
			
			// aapt resource value: 0x7f080017
			public const int czasBar = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int listView1 = 2131230746;
			
			// aapt resource value: 0x7f080009
			public const int progressBar1 = 2131230729;
			
			// aapt resource value: 0x7f080011
			public const int radioGroup1 = 2131230737;
			
			// aapt resource value: 0x7f080019
			public const int textView1 = 2131230745;
			
			// aapt resource value: 0x7f080000
			public const int txtCategoryName = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int txtCreate = 2131230725;
			
			// aapt resource value: 0x7f08001b
			public const int txtLogin = 2131230747;
			
			// aapt resource value: 0x7f080002
			public const int txtLoginLogin = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int txtLoginPassword = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int txtLub = 2131230727;
			
			// aapt resource value: 0x7f08001c
			public const int txtMail = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int txtPassword = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int txtPassword2 = 2131230750;
			
			// aapt resource value: 0x7f080016
			public const int txtPozostalo = 2131230742;
			
			// aapt resource value: 0x7f080010
			public const int txtQuestion = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int txtQuizNr = 2131230735;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int addCategory = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int menu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int quiz = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ranking = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int register = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int selectCategory = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int idUser = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070003
			public const int AppStyle_Light = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int ListFont = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int dialog_login_animation = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
